frontend: Upgrade dependencies
This is to get the latest security and other updates.

Note that webpack >= 5 does not work with sapper, I'm not sure why - I
plan to wait for svelte-next as a solution.

    resolve 'internal/shared' in '/Users/pgjones/pgjones_dev/frontend/src/node_modules/@sapper'
      using description file: /Users/pgjones/pgjones_dev/frontend/package.json (relative path: ./src/node_modules/@sapper)
        using description file: /Users/pgjones/pgjones_dev/frontend/package.json (relative path: ./src/node_modules/@sapper/internal/shared)
          /Users/pgjones/pgjones_dev/frontend/src/node_modules/@sapper/internal/shared doesn't exist
    webpack://pgjones_dev_frontend/./src/node_modules/@sapper/server.mjs?:7
    Object(function webpackMissingModule() { var e = new Error("Cannot find module './internal/manifest-server'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
                                                                                                                                                ^

    Error: Cannot find module './internal/manifest-server'
        at webpackMissingModule (webpack://pgjones_dev_frontend/./src/node_modules/@sapper/server.mjs?:7:50)
        at eval (webpack://pgjones_dev_frontend/./src/node_modules/@sapper/server.mjs?:7:151)
        at Module../src/node_modules/@sapper/server.mjs (/Users/pgjones/pgjones_dev/frontend/__sapper__/dev/server/server.js:1122:1)
        at __webpack_require__ (/Users/pgjones/pgjones_dev/frontend/__sapper__/dev/server/server.js:1314:42)
        at eval (webpack://pgjones_dev_frontend/./src/server.js?:5:72)
        at Module../src/server.js (/Users/pgjones/pgjones_dev/frontend/__sapper__/dev/server/server.js:1136:1)
        at __webpack_require__ (/Users/pgjones/pgjones_dev/frontend/__sapper__/dev/server/server.js:1314:42)
        at /Users/pgjones/pgjones_dev/frontend/__sapper__/dev/server/server.js:1377:18
        at Object.<anonymous> (/Users/pgjones/pgjones_dev/frontend/__sapper__/dev/server/server.js:1378:12)
        at Module._compile (internal/modules/cjs/loader.js:1200:30) {
      code: 'MODULE_NOT_FOUND'
    }